services:
  - type: web
    name: tim-portfolio
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
